### ISSUE TITLE
Equivalence Checking - SystemC vs. Generated SystemVerilog

### ISSUE THREAD

**Issue by ShashankVM** [intel/systemc-compiler#12]
Greetings,

This is a feature request for equivalence checking of the synthesized SystemVerilog code vs the SystemC design. Is such an enhancement planned? 

Regards,
Shashank V M

**Comment by mikhailmoiseev** [comment]
It needs some volunteer for this work. If you are interested in that, can discuss the details.

**Comment by ShashankVM** [comment]
@mikhailmoiseev yes, I'll be happy to work on this project.
