### ISSUE TITLE
Clarification of 7.1 Memory wrapper

### ISSUE THREAD

**Issue by xlef13** [intel/systemc-compiler#55]
Hi,

currently I am implementing a simple Cache module intended to be synthesized for a Xilinx Zynq-7000.
I would like to map the register representing the cache's memory to the block ram provided by my FPGA.

The relevant Code Section currently looks like this
```
class MBankRam : ::sc_core::sc_module {
  sc_uint<32>  ram_[2048];
};
```

The HLS converts this to
```
logic [31:0] ram_[2048];
logic [31:0] ram__next[2048];
...
```

The ICSC Manua 7.1 Memory wrapper mentions a common interface for memory access. However, quite honestly, I have a hard time getting this to work with in code. Can/should this be used in this case?
Is there a dedicated method for implementing registers that should be mapped to block ram?

Greetings

**Comment by mikhailmoiseev** [comment]
Hi,

The way you are using is correct. Suppose a Xilinx tool could map register to a ram block.
Memory wrapper described in Chapter 7.1.  is not open-sourced yet. Have updated the User guide w/o this chapter.

-Mikhail.
