### ISSUE TITLE
export SystemVerilog modules to multiple files?

### ISSUE THREAD

**Issue by pmerz1** [intel/systemc-compiler#68]
Is there a way for ICSC not to write all SystemVerilog modules to one file? 

I think sometimes it would be more convenient to split the modules into several files to make them easier to read.

What do you think?

**Comment by mikhailmoiseev** [comment]
No, only one SV file is generated. From my expirience working with one file is more convinient, specially for designs with hundreds of mudules. 
What advantages of multiple files do you see?

**Comment by mikhailmoiseev** [comment]
Do you think it is possible to write a script to split one SV file into multiple files by keywords module/endmodule?
I could add a low priority ticket for that, but cannot promise to implement it soon.

**Comment by pmerz1** [comment]
I am using a short script doing this as a workaround. 

And I have no problem if you create a low priority ticket for this.

**Comment by mikhailmoiseev** [comment]
Sounds good. Will update you when it is completed.
