### ISSUE TITLE
Instructions for SystemC simulation and viewing SV file does not work.

### ISSUE THREAD

**Issue by ShashankVM** [intel/systemc-compiler#9]
Greetings,

1. There is a minor error in the Linux commands for SystemC simulation. I have made a [pull-request](https://github.com/intel/systemc-compiler/pull/11) to fix that.
2. The SystemC simulation of counter does not stop because there is no time limit. I have fixed that and enhanced the testbench so that the user can get feedback on the example simulation. This is included in my pull-request.

**Comment by ShashankVM** [comment]
Currently I have closed my pull-request since users might remove the build directory. I will check again and reopen my pull-request.

**Comment by ShashankVM** [comment]
@mikhailmoiseev  are pull requests welcome?

**Comment by ShashankVM** [comment]
Hi @mikhailmoiseev : The Linux commands in the documentation don't work. So I made a pull request to fix it. I've also modified the counter testbench so that it stops and prints the output values.

**Comment by mikhailmoiseev** [comment]
Hi @ShashankVM. Thank you for your effort. I will check your pull request near weeks.
